version: '3.8'

services:
  verify-cert-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: verify-cert-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - POLYGON_MUMBAI_RPC_URL=https://rpc-mumbai.maticvigil.com
      - CONTRACT_ADDRESS=0x742d35Cc6634C0532925a3b8D4C9db96C4b4d4d4
      - PRIVATE_KEY=${PRIVATE_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_NAME=VerifyCert
      - FROM_EMAIL=${FROM_EMAIL}
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - ./backend/logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - verify-cert-network

networks:
  verify-cert-network:
    driver: bridge